name: backups

x-environment: &environment
  TZ: ${TZ:-America/Sao_Paulo}
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

x-common: &common
  restart: unless-stopped
  networks:
    - backups
    - database
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

services:
  zerobyte:
    <<: *common
    image: ghcr.io/nicotsx/zerobyte:v0.42
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "${TAILSCALE_IP}:4096:4096"
    security_opt:
      - apparmor:unconfined
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      <<: *environment
      BASE_URL: http://${TAILSCALE_IP}:4096
      APP_SECRET: ${APP_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte

networks:
  backups:
    external: true
    name: network_backup
  database:
    external: true
    name: network_database
