global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node-exporter
    dns_sd_configs:
      - names:
          - tasks.observabilidade_node-exporter
        type: A
        port: 9100

    relabel_configs:
      - source_labels:
          - __meta_dns_name
        target_label: dns_name

  - job_name: cadvisor
    dns_sd_configs:
      - names:
          - tasks.observabilidade_cadvisor
        type: A
        port: 8080
